name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: bahmutov/npm-install@v1
      - run: git remote set-url origin --add https://$NODI_BOT_TOKEN@github.com/nodi-bot/documentation
        env:
          NODI_BOT_TOKEN: ${{ secrets.NODI_BOT_TOKEN }}
      - run: git push
